osx_image: xcode7
language: objective-c
install:
- gem install cocoapods -v 0.39.0 --no-document

before_script:
- cd Example
- pod install

xcode_workspace: Popover.xcworkspace
xcode_scheme: PopoverExample
xcode_sdk: iphonesimulator
