osx_image: xcode8.2
language: objective-c
install:
- gem install cocoapods -v 1.1.1 --no-document

before_script:
- cd Example
- pod install

script:
- xcodebuild -workspace Popover.xcworkspace -scheme "PopoverExample" -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s' build test | xcpretty